
create table if not exists public.order_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  status text not null default 'Nuevo',
  service_type text not null default 'Delivery',
  customer_name text,
  phone text not null,
  address text,
  notes text,
  items jsonb not null default '[]'::jsonb,
  estimated_total numeric not null default 0,
  delivery_fee numeric not null default 0,
  estimated_minutes int,
  public_token uuid not null default gen_random_uuid(),
  mapped_order_id bigint,
  reject_reason text
);

create index if not exists idx_order_requests_phone on public.order_requests(phone);
create index if not exists idx_order_requests_token on public.order_requests(public_token);

-- Si ya creaste la tabla y la app no la ve: ejecutar en SQL editor:
-- NOTIFY pgrst, 'reload schema';
