-- 20_promotions_seed.sql
-- Seed de promos "vendedoras" (puedes editarlas desde Admin > Promos)
insert into public.promotions (slug,name,badge,headline,subheadline,body,price_text,detail_text,cta_label,cta_code,wa_message,thumb_url,image_url,sort_index,active)
values
('carlos10','Promo Carlos','TOP','¡CARLOS TE ENGAÑA! 💔','...pero tú no te quedas sin cena.','No dejes que te rompan el corazón (ni el estómago). Consuélate con nuestra personal crujiente de 16 cm.','S/ 10','Pizza personal + bebida (hoy)','Pedir mi pizza ahora','CARLOS10','Hola 👋 Quiero la promo CARLOS (S/10). ¿Me ayudas a pedir?','/promos/promo_placeholder_1.svg','/promos/promo_placeholder_2.svg',1,true),
('combo2','Combo 2x Personales','AHORRA','Dos personales, cero drama.','Ideal para compartir (o no).','Dos pizzas personales para resolver la noche: elige sabores y suma bebida.','S/ 24','2 personales (elige sabores)','Quiero el combo','COMBO2','Hola 👋 Quiero el combo 2x personales.','/promos/promo_placeholder_1.svg','/promos/promo_placeholder_2.svg',2,true),
('familiar39','Familiar + Bebida','FAMILIAR','Noche de peli + pizza.','Para 3–4 personas.','Una familiar para la casa: más queso, más amor, más antojo.','S/ 39','Familiar + bebida','Pedir familiar','FAMILIAR39','Hola 👋 Quiero la promo familiar + bebida.','/promos/promo_placeholder_1.svg','/promos/promo_placeholder_2.svg',3,true),
('2x1wed','2x1 Miércoles','LIMITADA','2x1 SOLO HOY 🔥','Miércoles de antojo.','Válido solo miércoles. Sabores seleccionados. Stock limitado.','Desde S/ 39.90','2 pizzas (segunda GRATIS)','Pedir 2x1','2X1WED','Hola 👋 Quiero el 2x1 de miércoles (código 2X1WED).','/promos/promo_placeholder_1.svg','/promos/promo_placeholder_2.svg',4,true),
('pareja50','Combo Pareja','NUEVA','NOCHE DE PAREJA 💘','Para 2 (o para ti 😄).','2 medianas + 2 bebidas. Elige sabores y te lo llevamos calientito.','S/ 49.90','2 medianas + 2 bebidas','Quiero el combo','PAREJA50','Hola 👋 Quiero el Combo Pareja (código PAREJA50).','/promos/promo_placeholder_1.svg','/promos/promo_placeholder_2.svg',5,true),
('office30','Combo Oficina','NUEVA','ALMUERZO EXPRESS ⚡','Rápido, rico y rendidor.','2 personales + bebida para resolver el almuerzo en minutos.','S/ 29.90','2 personales + bebida','Pedir express','OFFICE30','Hola 👋 Quiero el Combo Oficina (código OFFICE30).','/promos/promo_placeholder_1.svg','/promos/promo_placeholder_2.svg',6,true),
('famxxl','Combo Familiar XXL','TOP','COMBO FAMILIAR XXL 🍕🥤','Para 6–8 personas.','3 familiares + 2 bebidas 1.5L. Perfecto para reunión.','S/ 119.90','3 familiares + 2 bebidas 1.5L','Quiero el XXL','FAMXXL','Hola 👋 Quiero el Combo Familiar XXL (código FAMXXL).','/promos/promo_placeholder_1.svg','/promos/promo_placeholder_2.svg',7,true)
on conflict (slug) do nothing;
