-- 30_fix_promos_dual_system.sql
-- 1) UPSERT a public.promotions (para /promos y /promo/:slug)
-- 2) Setea config.promo_promos (para /promo landing multi-campañas)
-- Edita precios (S/ 0.00) y WhatsApp en config o en Admin.

-- A) public.promotions
insert into public.promotions as pr (slug,name,badge,headline,subheadline,price_text,detail_text,cta_label,cta_code,wa_message,image_url,thumb_url,active,starts_at,ends_at,sort_index) values ('2x1-hawaiana','2x1 Hawaiana','2x1','Paga 1 y llévate 2','Hawaiana (jamón + piña)','S/ 0.00','2 pizzas (mismo tamaño)','Pedir ahora','2X1HAW','Hola 👋 Quiero la promo 2x1 Hawaiana. ¿Me ayudas a pedir?','/promos/2x1_hawaiana_banner.svg','/promos/2x1_hawaiana_square.svg',true,null,null,10) on conflict (slug) do update set name=excluded.name,badge=excluded.badge,headline=excluded.headline,subheadline=excluded.subheadline,price_text=excluded.price_text,detail_text=excluded.detail_text,cta_label=excluded.cta_label,cta_code=excluded.cta_code,wa_message=excluded.wa_message,image_url=excluded.image_url,thumb_url=excluded.thumb_url,active=true,starts_at=null,ends_at=null,sort_index=excluded.sort_index;
insert into public.promotions as pr (slug,name,badge,headline,subheadline,price_text,detail_text,cta_label,cta_code,wa_message,image_url,thumb_url,active,starts_at,ends_at,sort_index) values ('2x1-pepperoni','2x1 Pepperoni','2x1','Paga 1 y llévate 2','Pepperoni (full queso)','S/ 0.00','2 pizzas (mismo tamaño)','Pedir ahora','2X1PEP','Hola 👋 Quiero la promo 2x1 Pepperoni. ¿Me ayudas a pedir?','/promos/2x1_pepperoni_banner.svg','/promos/2x1_pepperoni_square.svg',true,null,null,11) on conflict (slug) do update set name=excluded.name,badge=excluded.badge,headline=excluded.headline,subheadline=excluded.subheadline,price_text=excluded.price_text,detail_text=excluded.detail_text,cta_label=excluded.cta_label,cta_code=excluded.cta_code,wa_message=excluded.wa_message,image_url=excluded.image_url,thumb_url=excluded.thumb_url,active=true,starts_at=null,ends_at=null,sort_index=excluded.sort_index;
insert into public.promotions as pr (slug,name,badge,headline,subheadline,price_text,detail_text,cta_label,cta_code,wa_message,image_url,thumb_url,active,starts_at,ends_at,sort_index) values ('2x1-americana','2x1 Americana','2x1','Paga 1 y llévate 2','Americana (jamón + queso)','S/ 0.00','2 pizzas (mismo tamaño)','Pedir ahora','2X1AME','Hola 👋 Quiero la promo 2x1 Americana. ¿Me ayudas a pedir?','/promos/2x1_americana_banner.svg','/promos/2x1_americana_square.svg',true,null,null,12) on conflict (slug) do update set name=excluded.name,badge=excluded.badge,headline=excluded.headline,subheadline=excluded.subheadline,price_text=excluded.price_text,detail_text=excluded.detail_text,cta_label=excluded.cta_label,cta_code=excluded.cta_code,wa_message=excluded.wa_message,image_url=excluded.image_url,thumb_url=excluded.thumb_url,active=true,starts_at=null,ends_at=null,sort_index=excluded.sort_index;
insert into public.promotions as pr (slug,name,badge,headline,subheadline,price_text,detail_text,cta_label,cta_code,wa_message,image_url,thumb_url,active,starts_at,ends_at,sort_index) values ('combo-familiar','Combo Familiar','TOP VENTA','2 medianas + 1.5L','Ideal para 4 personas','S/ 0.00','2 pizzas medianas + bebida','Comprar combo','FAM','Hola 👋 Quiero el Combo Familiar. ¿Me ayudas a pedir?','/promos/combo_familiar_landscape.svg','/promos/combo_familiar_square.svg',true,null,null,2) on conflict (slug) do update set name=excluded.name,badge=excluded.badge,headline=excluded.headline,subheadline=excluded.subheadline,price_text=excluded.price_text,detail_text=excluded.detail_text,cta_label=excluded.cta_label,cta_code=excluded.cta_code,wa_message=excluded.wa_message,image_url=excluded.image_url,thumb_url=excluded.thumb_url,active=true,starts_at=null,ends_at=null,sort_index=excluded.sort_index;

-- B) Landing /promo: config key promo_promos (JSON)
-- Nota: ajusta el nombre de tabla/columna si tu config se llama distinto.
insert into public.config as c (key, value) values ('promo_active','true') on conflict (key) do update set value=excluded.value;
insert into public.config as c (key, value) values ('promo_promos','[{"id": "2x1-hawaiana", "name": "2x1 Hawaiana", "active": true, "priority": 10, "headline": "Paga 1 y llévate 2", "subheadline": "Hawaiana (jamón + piña)", "body": "2 pizzas (mismo tamaño)", "price_text": "S/ 0.00", "detail_text": "2 pizzas (mismo tamaño)", "cta_label": "Pedir ahora", "cta_code": "2X1HAW", "phone": "", "wa_number": "", "wa_message": "Hola 👋 Quiero la promo 2x1 Hawaiana. ¿Me ayudas a pedir?", "hero_image": "/promos/2x1_hawaiana_banner.svg", "theme": "dark", "start_at": null, "end_at": null, "info_url": "/promo/2x1-hawaiana"}, {"id": "2x1-pepperoni", "name": "2x1 Pepperoni", "active": true, "priority": 11, "headline": "Paga 1 y llévate 2", "subheadline": "Pepperoni (full queso)", "body": "2 pizzas (mismo tamaño)", "price_text": "S/ 0.00", "detail_text": "2 pizzas (mismo tamaño)", "cta_label": "Pedir ahora", "cta_code": "2X1PEP", "phone": "", "wa_number": "", "wa_message": "Hola 👋 Quiero la promo 2x1 Pepperoni. ¿Me ayudas a pedir?", "hero_image": "/promos/2x1_pepperoni_banner.svg", "theme": "dark", "start_at": null, "end_at": null, "info_url": "/promo/2x1-pepperoni"}, {"id": "2x1-americana", "name": "2x1 Americana", "active": true, "priority": 12, "headline": "Paga 1 y llévate 2", "subheadline": "Americana (jamón + queso)", "body": "2 pizzas (mismo tamaño)", "price_text": "S/ 0.00", "detail_text": "2 pizzas (mismo tamaño)", "cta_label": "Pedir ahora", "cta_code": "2X1AME", "phone": "", "wa_number": "", "wa_message": "Hola 👋 Quiero la promo 2x1 Americana. ¿Me ayudas a pedir?", "hero_image": "/promos/2x1_americana_banner.svg", "theme": "dark", "start_at": null, "end_at": null, "info_url": "/promo/2x1-americana"}, {"id": "combo-familiar", "name": "Combo Familiar", "active": true, "priority": 2, "headline": "2 medianas + 1.5L", "subheadline": "Ideal para 4 personas", "body": "2 pizzas medianas + bebida", "price_text": "S/ 0.00", "detail_text": "2 pizzas medianas + bebida", "cta_label": "Comprar combo", "cta_code": "FAM", "phone": "", "wa_number": "", "wa_message": "Hola 👋 Quiero el Combo Familiar. ¿Me ayudas a pedir?", "hero_image": "/promos/combo_familiar_landscape.svg", "theme": "dark", "start_at": null, "end_at": null, "info_url": "/promo/combo-familiar"}]') on conflict (key) do update set value=excluded.value;
